from typing import Optional


def get(key: str, branch: Optional[str] = None, hversion: Optional[str] = None, output_path: Optional[str] = None): ...
def put(key: str, branch: str, str: Optional[str] = None, input_path: Optional[str] = None): ...