name: Case Study - Autolearn
env:
  test_source_base: /home/mlcask/sgx/test-source/
  workspace_base: /home/mlcask/seccask-temp/
branches:
  - master
datasets:
  - dataset_autolearn
libraries:
  - autolearn_IG_v0.0
  - autolearn_IG_v0.0
  - autolearn_dependent_regression_v0.0
  - autolearn_dependent_regression_v0.0
  - autolearn_stable_v0.0
  - autolearn_stable_v0.0
  - autolearn_model_v0.0
  - autolearn_model_v0.0
pipeline:
  - { type: dataset, name: dataset_autolearn }
  - { type: library, name: autolearn_IG }
  - { type: library, name: autolearn_dependent_regression }
  - { type: library, name: autolearn_stable }
  - { type: library, name: autolearn_model }
tasks:
  - action: commit_libs

  - action: create_pipeline
    branch: master
    versions: [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
  - action: create_pipeline
    branch: master
    versions: [[0, 0], [0, 1], [0, 1], [0, 1], [0, 1]]
